// Build the Metacenter logo options (A–D) as SVG files.
//   node marketing/logo/build.mjs <outDir>
// Needs `opentype.js` and the `geist` font package resolvable from the working directory
// (the wordmark is outlined to paths, so the SVGs do not depend on installed fonts).
import fs from "node:fs";
import path from "node:path";
import opentype from "opentype.js";

const OUT = path.resolve(process.argv[2] ?? "marketing/logo");
const ttf = fs.readFileSync(
  process.env.GEIST_TTF ?? path.join(process.cwd(), "node_modules/geist/dist/fonts/geist-sans/Geist-SemiBold.ttf"),
);
const font = opentype.parse(ttf.buffer.slice(ttf.byteOffset, ttf.byteOffset + ttf.byteLength));

// Site palette (web/app/globals.css)
export const THEMES = {
  dark: { bg: "#07090c", ink: "#e9eef2", accent: "#26a596" },
  light: { bg: "#f7f6f2", ink: "#12161c", accent: "#008a7b" },
  mono: { bg: "none", ink: "currentColor", accent: "currentColor" },
};

// The chosen mark (option C, picked 2026-09-19) on a 32×32 grid. `i` = ink, `a` = accent.
// Options A, B and D are no longer built; their files stay in marketing/logo/{A,B,D}/ as history,
// together with options.png, the comparison sheet the choice was made from.
export const MARKS = {
  C: {
    name: "M monogram",
    note: "An M whose centre dips like a keel, with the metacentre point above it.",
    svg: (i, a) =>
      `<path d="M5.5 25V9.5L16 20.5L26.5 9.5V25" fill="none" stroke="${i}" stroke-width="3.4" stroke-linecap="round" stroke-linejoin="round"/>` +
      `<circle cx="16" cy="7.4" r="3.2" fill="${a}"/>`,
  },
};
export const CHOSEN = "C";

const wordPath = (x, baseline, size) => {
  const p = font.getPath("Metacenter", x, baseline, size, { kerning: true, letterSpacing: -0.02 });
  return { d: p.toPathData(2), width: font.getAdvanceWidth("Metacenter", size, { kerning: true, letterSpacing: -0.02 }) };
};

export function markSvg(id, theme, { size = 32, background = false } = {}) {
  const t = THEMES[theme];
  const bg = background && t.bg !== "none" ? `<rect width="32" height="32" rx="7" fill="${t.bg}"/>` : "";
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="${size}" height="${size}">${bg}${MARKS[id].svg(t.ink, t.accent)}</svg>`;
}

export function lockupSvg(id, theme) {
  const t = THEMES[theme];
  const w = wordPath(42, 23.2, 21);
  const width = Math.ceil(42 + w.width + 2);
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} 32" width="${width * 4}" height="128">${MARKS[id].svg(t.ink, t.accent)}<path d="${w.d}" fill="${t.ink}"/></svg>`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  for (const id of Object.keys(MARKS)) {
    const dir = path.join(OUT, id);
    fs.mkdirSync(dir, { recursive: true });
    for (const theme of Object.keys(THEMES)) {
      fs.writeFileSync(path.join(dir, `mark-${theme}.svg`), markSvg(id, theme, { size: 256 }));
      fs.writeFileSync(path.join(dir, `lockup-${theme}.svg`), lockupSvg(id, theme));
    }
    fs.writeFileSync(path.join(dir, "favicon.svg"), markSvg(id, "dark", { size: 32, background: true }));
  }
  // the site's single logo asset, with colour slots filled per theme by the app
  const markJson = path.join(OUT, "..", "..", "web", "brand", "mark.json");
  fs.writeFileSync(
    markJson,
    JSON.stringify(
      {
        id: CHOSEN,
        note: "The single logo asset (generated by marketing/logo/build.mjs from option C). Swap this file to change the logo everywhere: site header, dashboard sidebar, docs header, favicons, OG/Twitter images, clip watermark and end card, X avatar and banner. `svg` is the inner markup of the viewBox; {ink} and {accent} are filled per theme.",
        viewBox: "0 0 32 32",
        svg: MARKS[CHOSEN].svg("{ink}", "{accent}"),
      },
      null,
      2,
    ) + "\n",
  );
  console.log("wrote", markJson);
  console.log("wrote", Object.keys(MARKS).join(", "), "to", OUT);
}
